########################################################################
spring.application.name=monatis
server.port=8082
########################################################################

## POSTGRESQL ##########################################################
#spring.datasource.url=jdbc:postgresql://localhost:5433/monatis
#spring.datasource.username=postgres
#spring.datasource.password=pgAdmin
########################################################################

## H2 DATABASE #########################################################

# restauration manuelle : runscript from 'C:\Users\odani\Desktop\MONATIS\test_sauvegarde\monatis-modifie.sql';
# chargement script simple columns nosettings to 'C:\Users\odani\Desktop\MONATIS\test_sauvegarde\script.sql';
# 
# sauvegarde manuelle : 

spring.datasource.url=jdbc:h2:file:./data/monatis
spring.datasource.username=sa
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
########################################################################

## JPA - HIBERNATE #####################################################
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
########################################################################

logging.level.fr.colline.monatis.controller.ControllerExceptionHandler=info
