#-RQST-TEC-0001 = Un problème technique est survenu
#-RQST-TEC-0002 = Un problème est survenu lors du chargement d'initialisation de la base

#-RQST-BNQ-0001 = Aucune banque de nom ''{0}'' n''a été trouvée
#-RQST-BNQ-0002 = La banque ''{0}'' n'a pas pu être créée
#-RQST-BNQ-0003 = La banque ''{0}'' n'a pas pu être modifiée
#-RQST-BNQ-0004 = La banque ''{0}'' n'a pas pu être supprimée
#-RQST-BNQ-0005 = Une banque doit obligatoirement avoir un nom

#-RQST-BEN-0001 = Aucun bénéficiaire de nom ''{0}'' n''a été trouvé
#-RQST-BEN-0002 = Le bénéficiaire ''{0}'' n''a pas pu être créé
#-RQST-BEN-0003 = Le bénéficiaire ''{0}'' n''a pas pu être modifié
#-RQST-BEN-0004 = Le bénéficiaire ''{0}'' n'a pas pu être supprimé
#-RQST-BEN-0005 = Un bénéficiaire doit obligatoirement avoir un nom

#-RQST-CAT-0001 = Aucune catégorie de nom ''{0}'' n''a été trouvée
#-RQST-CAT-0002 = La catégorie ''{0}'' n''a pas pu être créée
#-RQST-CAT-0003 = La catégorie ''{0}'' n''a pas pu être modifiée
#-RQST-CAT-0004 = La catégorie ''{0}'' n''a pas pu être supprimée
#-RQST-CAT-0005 = Une catégorie doit obligatoirement avoir un nom

#-RQST-SSC-0001 = Aucune sous-categorie de nom ''{0}'' n''a été trouvée
#-RQST-SSC-0002 = La sous-catégorie ''{0}'' n''a pas pu être créée
#-RQST-SSC-0003 = La sous-catégorie ''{0}'' n''a pas pu être modifiée
#-RQST-SSC-0004 = La sous-categorie ''{0}'' n''a pas pu être supprimée
#-RQST-SSC-0005 = Une sous-catégorie doit obligatoirement avoir un nom
#-RQST-SSC-0006 = Une sous-catégorie doit obligatoirement être associée à une catégorie déterminée par son nom

#-RQST-TIT-0001 = Aucun titulaire de nom ''{0}'' n''a été trouvé
#-RQST-TIT-0002 = Le titulaire ''{0}'' n''a pas pu être créé
#-RQST-TIT-0003 = Le titulaire ''{0}'' n''a pas pu être modifié
#-RQST-TIT-0004 = Le titulaire ''{0}'' n''a pas pu être supprimé
#-RQST-TIT-0005 = Un titulaire doit obligatoirement avoir un nom

#-RQST-CPT-0001 = Aucun compte d'identifiant ''{0}'' n''a été trouvé
#-RQST-CPT-0002 = Un compte de type de fonctionnement ''{0}'' est incompatible en dépense avec des opération de type ''{1}''
#-RQST-CPT-0003 = Un compte de type de fonctionnement ''{0}'' est incompatible en recette avec des opération de type ''{1}''
#-RQST-CPT-0004 = Le type de fonctionnement du compte ''{0}'' n''est pas géré
#-RQST-CPT-0005 = La classe du compte ''{0}'' n''est pas gérée
#-RQST-CPT-0006 = Aucun compte interne d'identifiant ''{0}'' n''a été trouvé
#-RQST-CPT-0007 = Le compte interne ''{0}'' n''a pas pu être créé
#-RQST-CPT-0008 = Le compte interne ''{0}'' n''a pas pu être modifié
#-RQST-CPT-0009 = Le compte interne ''{0}'' n''a pas pu être supprimé
#-RQST-CPT-0010 = La liste des titulaires du compte interne est obligatoire
#-RQST-CPT-0011 = Le compte interne ''{0}'' doit avoir une banque
#-RQST-CPT-0012 = Un compte interne doit avoir un identifiant
#-RQST-CPT-0013 = Un compte interne doit avoir un type
#-RQST-CPT-0014 = Aucun type de compte interne de code ''{0}'' n''a été trouvé
#-RQST-CPT-0015 = Le compte interne doit avoir au moins un titulaire
#-RQST-CPT-0016 = Aucun compte de tiers d'identifiant ''{0}'' n''a été trouvé
#-RQST-CPT-0017 = Le compte de tiers ''{0}'' n''a pas pu être créé
#-RQST-CPT-0018 = Le compte de tiers ''{0}'' n''a pas pu être modifié
#-RQST-CPT-0019 = Le compte de tiers ''{0}'' n''a pas pu être supprimé



